### ISSUE TITLE
Filter geometry by layer

### ISSUE THREAD

**Issue by bkvsy** [moethu/SketchUpNET#11]
Hi, is it possible to filter imported geometry in dynamo by layer name?

**Comment by moethu** [comment]
@bkvsy this is not implemented at the moment but I can add it

**Comment by bkvsy** [comment]
Great.
I'm looking for a solution for importing separate sketchup solid geometry modeled in one file to separate mass in revit ie. 4 blocks representing 4 different buildings. Right now that imported group of blocks becomes one mass in revit. And mass floor represents a connected sum of floors of all buildings in group. 
I can't find a better way rather than creating many separate skp files and importing all masses one by one.

**Comment by moethu** [comment]
@bkvsy just uploaded a new version handling it... at least on the highest level. You can have nested groups / instances / etc... and they all can have layers... so I just added a node giving you the model content by layername for the highest level of elements.
