### ISSUE TITLE
Gentle Feature Request: Sketchup.LoadModel solids output (components)

### ISSUE THREAD

**Issue by kv2** [moethu/SketchUpNET#14]
Hello Maximilian,

I am wondering if it would be possible to load sketchup components as solids, or at least as @L2 lists of surfaces. Right now the model comes in as a large list of surfaces. Joining surfaces by polysurfaces and making solids out of those to be exported into revit only works as long as no geometry intersects. 

Importing something such as this, and having each object show up requires importing each component separately and moving them into the same position within Revit: 

![image](https://user-images.githubusercontent.com/6821322/30495564-584ecfdc-9a01-11e7-8a60-b6598e8ec0c7.png)

Having that feature would enable me to be to create solids out of sketchup models (such as furniture made by a landscape architect in sketchup, where the seat of the chair (a component) intersects the arms of the chair (another component)). By sorting each component into its own list, we would be able to bring in those components as individual solids into our revit environment. 

If you think this is doable, I would love to work with you on this and try and write it. 

Thanks,
kv2

**Comment by kv2** [comment]
I took a look at the code, and your cpp wrapper supports components - ./SketchUp/SketchUpNET/SketchUpNET/Component.cpp
./SketchUp/SketchUpNET/SketchUpNET/SketchUpNET.cpp 
`Components = gcnew System::Collections::Generic::Dictionary<String^,Component^>();

			// Get all Components
			size_t compCount = 0;
			SUModelGetNumComponentDefinitions(model, &compCount);

			if (compCount > 0) {
				std::vector<SUComponentDefinitionRef> comps(compCount);
				SUModelGetComponentDefinitions(model, compCount, &comps[0], &compCount);

				for (size_t i = 0; i < compCount; i++) {
					Component^ component = Component::FromSU(comps[i], includeMeshes, Materials);
					Components->Add(component->Guid, component);
				}
			}
`

Allows the retrieval of components.

**Comment by kv2** [comment]
Never-mind! I read more of the code, and it turns out you support components as "instances" you also support groups. Thanks so much! 

Issue is now closed.

**Comment by moethu** [comment]
@kv2 sorry for the delay, I was very busy. Is this solved or do you want some changes?
