### ISSUE TITLE
Doesn't work on all skp files?

### ISSUE THREAD

**Issue by Kevinator123** [moethu/SketchUpNET#17]
For some reason some skp files are perfectly readable except for the fact that it shows 0 surfaces, all the other stuff is there, like components, instances, materials, etc. But for some reason some files return 0 surfaces.

**Comment by moethu** [comment]
@Kevinator123 did you check if the files are containing instances instead? In Skp you can model geometry like surfaces on root level but you can also wrap everything in instances, so you wouldn't see any surfaces in the model.

**Comment by Kevinator123** [comment]
Yes there are instances but how do I get the vertices out of them?

**Comment by moethu** [comment]
Yes, an instance is a placed component: so instance -> component -> surfaces or curves.
And of course, components can be nested.
What kind of vertices are you looking for? Mesh vertices? Endpoints of curves?

**Comment by moethu** [comment]
If you want to get Meshes: Surface -> FaceMesh

**Comment by Kevinator123** [comment]
Mesh vertices, I'm trying to rebuild the mesh in Unity. So I'll also need the transform of each instance and the indices for each vertex (they should all be in the correct order if I read the sketchup forum right?). Have you ever considered having an integration with Assimp.net? Would be neat!

**Comment by moethu** [comment]
exactly, you just walk through all Components (on Model level) -> Surfaces -> FaceMesh and translate the Mesh into your format. The mesh definition is pretty simple: Normals, Vertices and Faces where Faces have 3 integers referring to the index of the vertices list.

**Comment by Kevinator123** [comment]
Ok thank you very much! For integration in Unity (at least the very basics of just the mesh) you need the vertices and their indices and that'll do. Thank you very much for your help!

**Comment by moethu** [comment]
btw. when you load the model keep in mind to set the includeMeshes option to true - otherwise you won't get meshes

**Comment by Kevinator123** [comment]
Is there any way of retrieving UV coordinates from the sketchup file? Because I can't seem to find any reference to anything related to UV's.
