### ISSUE TITLE
Cannot load models, when filepath contains special characters (ä, ö, ü, ß, ...)

### ISSUE THREAD

**Issue by Reaper90** [moethu/SketchUpNET#21]
As the title already says, it's not possible to load models when the filepath (filename and folderpath) contains special (in this case german) characters (ä, ö, ü, ß, ...). I'm using this library in a VB.NET WPF application and apart from this it works perfectly fine. But i couldn't find a solution to this on my applications side.

Is it possible to fix this problem? I'm not that experienced when it comes to C/C++...

**Comment by moethu** [comment]
Sorry to answer almost a year later... sure, that's not a big issue. I will have a look at it, or - create a PR if you can jump on it.

**Comment by moethu** [comment]
this has been fixed with #9
