### ISSUE TITLE
SketchUpNET could not load file or assembly

### ISSUE THREAD

**Issue by MxMostafa** [moethu/SketchUpNET#25]
my project c# console
i add the library on project and build success but when run the project get the error
could not load file or assembly.....
i change build mode x86 x64 any cpu
downloaded files SketchUpNET build 180818.zip

**Comment by moethu** [comment]
Hi @MxMostafa,
some questions regarding your build:
- which SketchUp API version did you build it with?
- which .NET Version did you use?

**Comment by moethu** [comment]
You can also try the latest version that I just built

**Comment by MxMostafa** [comment]
Hi @moethu 
I Send Email for you to ‫maximilian.o.e.thumfart@gmail.com‬
I Use 180818 version
i Download SketchUpNET-master 
and After Extract 
from SketchUpNET-master\SketchUp\API path
add the SketchUpAPI.dll to reference but get error 
'SketchUpAPI.dll could not be added. please make sure that the file is accessible. and that is a valid assembly or COM component '
from path 'SketchUpNET-master\SketchUp'
I Can Add 'SketchUpNET.dll' to reference and build  but when run get error  'can not load file or assembly  SketchUpNET.dll or one of its dependencies.'
my projcet console appplication .net 4.5.2

**Comment by moethu** [comment]
Hi @MxMostafa,
so you were able to build SketchUpNET successfully right?
I would recommend to follow the example projects which are already in the solution. Like SketchUpDynamo. It shows how to setup a project referring to all necessary libraries.
Please make sure that:
- you placed all the files into the same folder so there is no path issue
- the .NET version of your console app isn't lower than the .NET version of SketchUpNET
- you are are targeting the same arch as your SketchUpNET build

You can also check for the missing dependency using a dependency walker but to me it smells like a targeting wrong arch issue.

**Comment by moethu** [comment]
@MxMostafa I added a sample console app for you here: https://github.com/moethu/SketchUpNET/tree/master/SketchUpNETConsole

**Comment by MxMostafa** [comment]
thank you so much
in my language Persian :  "خیلی مردی"  Which English is    ' Very manly '
   "خیلی مردی" : A very thankful term
------------------
but i have a question
can i create plugin for sketchup with c# and add icon to sketchup menu or
 must for create plugin use ruby?
i will add button to sketchup menu and when click get current document and
get all material info and save to database
now i can use your library to get file information and can save data to
database just i will add button to sketchup menu
And finally, thank you again


‫‪moethu‬‏ <‪notifications@github.com‬‏> در تاریخ چهارشنبه ۲۷ مهٔ ۲۰۲۰ ساعت
۱۰:۳۳ نوشت:‬

**Comment by moethu** [comment]
@MxMostafa I'm glad I was able to help you.
If you want to add a button you'll have to go through ruby. But what you can do is the following thing I did in this project: https://github.com/grevit-dev/Grevit/blob/master/Grevit.SketchUp/grevit_send_menu.rb
Add a small ruby script adding a button to SketchUp which then calls a command line application. This way you can develop your application fully in C#.NET but call it from a button in SketchUp.
What I'm doing is simply saving the skp to a temp file and then reading it using the commandline app.
