### ISSUE TITLE
Rebuild GH package

### ISSUE THREAD

**Issue by pm-Architect** [moethu/SketchUpNET#30]
![Untitled](https://user-images.githubusercontent.com/63034836/86207722-bf72aa80-bb8c-11ea-9639-ab7d063d0955.png)
There seems to be some issue with the SketchUpNET.dll file when trying to run the Grasshopper file. @moethu can you please try rebuilding or modifying it so that it can run with Grasshopper for Rhino 6? I'm interested in contributing to the Grasshopper part of this project, but I'm no good with C++ at all. Thanks!

**Comment by moethu** [comment]
thanks @pm-Architect, I haven't built the GH version in while. will try to do that today.

**Comment by moethu** [comment]
@pm-Architect can you give it a try please?
do you want to join on developing the GH components?

**Comment by pm-Architect** [comment]
> @pm-Architect can you give it a try please?
> do you want to join on developing the GH components?

Absolutely! I'll give it a try today.
