### ISSUE TITLE
Having trouble creating a surface with a hole in it.

### ISSUE THREAD

**Issue by RonLight** [moethu/SketchUpNET#40]
I am getting weird results when trying to create a surface with a hole in it. In order to test my code, I created a square with a square hole in Sketchup. I opened the file and created code from all the values in the opened file (second part of code.txt). Finally I just tried opening the file and saving it and I get the same results. The shape is merged together.

Any suggestions? 
Thank you

![Input](https://user-images.githubusercontent.com/1970350/144517020-dc5be8cf-191e-4957-ab3f-1e5871ad3e5c.jpg)

	SketchUpNET.SketchUp skp = new SketchUpNET.SketchUp();
	if (skp.LoadModel("Input.skp"))
	{
		skp.WriteNewModel("new.skp", SKPVersion.V2017);
	}

![Output](https://user-images.githubusercontent.com/1970350/144517021-cee515c9-9b07-4cfa-bcf0-b223dbacd5f9.jpg)
[Sketchup.zip](https://github.com/moethu/SketchUpNET/files/7645631/Sketchup.zip)

**Comment by moethu** [comment]
thanks, I will have a look at this later today.

**Comment by moethu** [comment]
Thanks @RonLight for reporting this. Writing inner loops actually has never been implemented in this library, therefore I started implementing this feature in this branch: https://github.com/moethu/SketchUpNET/tree/feature/innersurfaceloops  - the test worked out fine already. please assure that your loops are closed and contain ordered edges without any duplicates on their start points. CW or CCW doesn't matter but for now they need to be ordered like this:
```
                OuterEdges.Edges.Add(new SketchUpNET.Edge(new Vertex(0, 0, 0), new Vertex(500, 0, 0), "Layer0"));
                OuterEdges.Edges.Add(new SketchUpNET.Edge(new Vertex(500, 0, 0), new Vertex(500, 500, 0), "Layer0"));
                OuterEdges.Edges.Add(new SketchUpNET.Edge(new Vertex(500, 500, 0), new Vertex(0, 500, 0), "Layer0"));
                OuterEdges.Edges.Add(new SketchUpNET.Edge(new Vertex(0, 500, 0), new Vertex(0, 0, 0), "Layer0"));
```

**Comment by moethu** [comment]
@RonLight did you find time testing this?

**Comment by RonLight** [comment]
Thanks for checking back. It did fix it for the example I gave. However, if I have something more complex, it fails.
At this point, I am simply opening the file and saving it.


![TestCubeInput](https://user-images.githubusercontent.com/1970350/151664811-ff1744a0-01e7-47b8-a6a9-2d3853d300be.png)
![TestCubeOutput](https://user-images.githubusercontent.com/1970350/151664814-71edef9d-ab84-4519-b504-89b994b94f02.png)
[TestCube.zip](https://github.com/moethu/SketchUpNET/files/7963899/TestCube.zip)
.

**Comment by moethu** [comment]
Thanks for testing this. Most users use this lib for either reading or writing but rarely both. Looks like the point order gets messed up either on read or on write. my suspicion is I created the issue by relying on ordered and directed edges in loops. I'm only adding the start point of each edge:
https://github.com/moethu/SketchUpNET/blob/master/SketchUpNET/Surface.cpp#L191
I'll change that to make sure the direction doesn't matter.

**Comment by RonLight** [comment]
I plan on using it to write, but I am using the read to help figure out
what I need to do. Have components been implemented? I notice I can read
components, but have not been able to write them.

Thanks
Ron

**Comment by moethu** [comment]
currently you cannot write them, that's right. but that shouldn't be too hard to add. what would you need? surfaces and edges?
about the reading and writing back issue: I gave it a go (https://github.com/moethu/SketchUpNET/commit/48be53985a9f180dff32b10a01c2a674f8caf5f0) and tried your file. it looks like this is becoming a rounding / tolerance issue. changing tolerances I can almost get the correct result. currently the library is converting from inches to metric on the fly, maybe I'll have to remove this in order to make re-writing work correctly.
