### ISSUE TITLE
Seems not to work with current version of Sketchup anymore

### ISSUE THREAD

**Issue by fstandhartinger** [moethu/SketchUpNET#5]
Hi there!
Thanks for the great work! I tried to get this working and have been able to build and run a console .NET app that uses your SketchUpNET library, but I have not been able to load a .SKP file that was created with a recent version of sketchup.
I guess this is probably because the library is implemented for an outdated sketchup api version, right?
Is there any chance you could provide it for the current version of sketchup?
Or could I send you the .SKP file so that you can tell me what I am doing wrong? 
I would also be ok to pay you as an compensation for your efforts if you can help...
Thanks and best regards.
Florian

**Comment by moethu** [comment]
@fstandhartinger thanks for reporting this. I never built it with SKP2017 I think, will build and check with the latest version this weekend.

**Comment by fstandhartinger** [comment]
Thanks a lot! But I have just run another test, and I don't know what I have done wrong last time I tried, but this time I have been able to load the .SKP file! So no real need anymore from my side.
By the way: Do you have experience with Unity (the game engine)? I am planning to implement a module to import Sketchup models to unity Meshes and GameObjects. You don't have anything like that available by luck, don't you?
Best regards Florian

**Comment by moethu** [comment]
sadly not, but it should be quite straight forward since most of the geometry definitions are quite simple. On meshes you'll just need the points and faces with ids referencing the points. I can add a method to export all the faces as meshes from SKP to C# if this helps?

**Comment by fstandhartinger** [comment]
Wow, thanks for the offer, sure that would be highly appreciated! Thanks alot!

What I am finally aiming for is something similar to this ObjImporter script for unity, which can import an .OBJ file:
[OBJ Omporter for Unity](http://wiki.unity3d.com/index.php?title=ObjImporter)
The code for the mesh creation seems kind of straigtforward to me.
The unity mesh object seems to be pretty self explanatory, if you look at these initialization lines:
        mesh.triangles = new int[triangles];
        mesh.vertices = new Vector3[vertices];
        mesh.uv = new Vector2[vt];
        mesh.normals = new Vector3[vn];
        mesh.faceData = new Vector3[face];
Also the Mesh class in unity is well documented [here]https://docs.unity3d.com/ScriptReference/Mesh.html).

If you feel like implementing any kind of "Exporting to a Mesh object" method, I'd be very gratefull! 
If you don't, thanks anyhow for sharing this excellent library!

**Comment by fstandhartinger** [comment]
If you consider implementing a complete .Skp to Unity Import, or help me to implement it, dou can also just contact me at stanzy at gmx de, if you like we can talk about what I could pay (or donate) you for your help! Best regards Florian

**Comment by moethu** [comment]
@fstandhartinger implemented meshes in https://github.com/moethu/SketchUpNET/commit/a3c5afc2cf267dc7989c48adb2cd66ad1d362f23

**Comment by Kevinator123** [comment]
@fstandhartingner, did you get it to work? And do you mind sharing how you got it to work? I can't seem to get it to read a SKP file but my program doesn't throw any errors, it just doesn't do anything at all.

**Comment by moethu** [comment]
@Kevinator123 can you describe your issue in a bit more detail please? Did you build the lib yourself? Did you load a binary? Which program are you talking about?

**Comment by Kevinator123** [comment]
So I'm writing my own program in C# that would allow the user to drag an skp file onto it and view it in VR, but for that to work I need to be able to read the model from the SKP file without opening sketchup. This is where your library would come in handy, unfortunately I can't get it to work. I can't build it myself, says that it can't find slapi.h, even though the sketchupapi lib and dll are in there. And when I use the latest release of your dll it just doesn't do anything. For test purposes I have a text box in my program in which you can drag a file, if you drag a .txt file it will print out all the lines in the file, so I thought I'd write out all the vertices for test purpose of a skp file but from the moment I use anything from the SketchUpNet dll nothing works, the program starts and I can type in the textbox but when I drag a file onto it it just doesn't do anything, doesn't throw an error, doesn't freeze, literally just unaffected.

**Comment by moethu** [comment]
Let me build it and commit some changes to the environment - for building it you'll have to install the SkpSDK. And you'll have to build it because the binaries are very outdated.

**Comment by moethu** [comment]
@Kevinator123 please try with the latest

**Comment by Kevinator123** [comment]
So I downloaded the latest version, couldn't build it, again SketchUpAPI/slapi.h missing. So I tried replacing the existing SketchUpAPI.lib with the latest, still the same error.

**Comment by moethu** [comment]
You should check all paths in the project's properties - check the output window, maybe it's giving you a hint where its looking for this header file. If not, I can build you a binary: what SketchUp Version do you need?

**Comment by Kevinator123** [comment]
I have all the files in the same folder but it's still throwing an error 
![image](https://user-images.githubusercontent.com/17850642/44313930-5e66e100-a411-11e8-95c6-d9bf1a3defff.png)

**Comment by Kevinator123** [comment]
In dependencywalker I get this: 
![image](https://user-images.githubusercontent.com/17850642/44340627-b7705c80-a485-11e8-966e-308a22e0884a.png)
And I have installed the latest version of VCredist

**Comment by Kevinator123** [comment]
![image](https://user-images.githubusercontent.com/17850642/44397851-04196d80-a542-11e8-964c-96a8c9c6568c.png)
This is what my project looks like, when I run it and drag a file on it to read I get the following error:
![image](https://user-images.githubusercontent.com/17850642/44397902-2c08d100-a542-11e8-9d8c-7e5a9800de64.png)
And when I open the SketchUpNET dll in dependencywalker I get this:
![image](https://user-images.githubusercontent.com/17850642/44397940-48a50900-a542-11e8-8cce-11c3d55c9b46.png)

**Comment by Kevinator123** [comment]
Nevermind, got it to work, apparently I had to add the SketchUpAPI dll and others in the build folder, didn't know that, was putting it in the project folder (still very new to .NET development, only worked with Unity). Anyways, thank you very much for your help and time, I really appreciate it.

**Comment by Kevinator123** [comment]
Ok so another problem, loading your test skp's is no problem what so ever, but loading any other skp is doing nothing. I tried "Reformatting" them to version 2017 but that didn't work either.
