### ISSUE TITLE
Add Materials export

### ISSUE THREAD

**Issue by moethu** [moethu/SketchUpNET#7]

**Comment by moethu** [comment]
@fstandhartinger just added materials.

**Comment by moethu** [comment]
Each surface has a Back and FrontMaterial

**Comment by moethu** [comment]
Are you going to match by name or color? I added the color as ARGB as well

**Comment by fstandhartinger** [comment]
@moethu: Wow, incredible performance! I will match textures by name. Am absolutely happy with what you did there!
great thanks + kudos!
