### ISSUE TITLE
bug: SketchUp.LoadModel don't support other country's language

### ISSUE THREAD

**Issue by codeex** [moethu/SketchUpNET#9]
Scene:
SketchUp skp = new SketchUp();
 var bRtn = skp.LoadModel(“c:\\TestModel - 副本.skb”, true);
but return false。
in bool LoadModel(System::String^ filename, bool includeMeshes),
Fix it：
		
			#pragma region Convert System::String to const char* by utf8 encoding
			array<unsigned char>^ bytes = System::Text::Encoding::UTF8->GetBytes(filename);
			char* path = new char[bytes->Length + 1];
			path[bytes->Length] = 0;
			int i = 0;
			for each(unsigned char c in bytes) {
				path[i++] = c;
			}
                        //complete to delete path.
			#pragma endregion

			//msclr::interop::marshal_context oMarshalContext;			
			//const char* path = oMarshalContext.marshal_as<const char*>(filename);
			SUInitialize();

**Comment by moethu** [comment]
@codeex I changed this some time ago, is this still an issue?
